### ISSUE TITLE
pronunciation errors, punctuation errors.

### ISSUE THREAD

**Issue by RubenManurung** [albirrkarim/react-speech-highlight-demo#3]
we tried the demo through https://react-speech-highlight.vercel.app/#example3, we have an article feature that we want to integrate with this package, the data from the article is in the form of html tags generated from ckeditor and we tried this package with the generated html that we have but there are some errors such as pronunciation errors, punctuation errors.

this is the example:
```<div style="grid-area: cnt / cnt / cnt / cnt;"><article id="myArticle" class="prose prose-img:rounded-xl md:mt-10 mb-8 max-w-none inline  "><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Pendaftaran PPPK tahun 2023 telah diumumkan resmi. Bersamaan dengan pengumuman </span><a href="https://www.qubisa.com/article/gaji-pns-2022-naik-begini-cara-meminta-kenaikan-gaji"><span style="background-color: transparent; color: rgb(0, 0, 0);">seleksi CPNS</span></a><span style="background-color: transparent; color: rgb(0, 0, 0);"> 2023, pemerintah juga telah mengumumkan jadwal dan persyaratan seleksi PPPK 2023. Informasi ini sangat penting untuk dicatat agar kamu bisa mempersiapkan diri dengan lebih baik untuk mengikuti seleksi tersebut.&nbsp;</span></p><h2><span style="background-color: transparent; color: rgb(0, 0, 0);">Jadwal Pendaftaran PPPK 2023</span></h2><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Pendaftaran PPPK akan dimulai pada tanggal 17 September 2023. Jadwal ini telah diumumkan dalam Surat Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (PANRB) Nomor: B/1871/M.SM.01.00/2023. Badan Kepegawaian Negara (BKN) telah mengumumkannya sejak 21 Agustus 2023. Peserta seleksi PPPK akan menjalani beberapa rangkaian tes, termasuk tes kompetensi teknis sebanyak 90 soal, seleksi kompetensi manajerial 25 soal, kompetensi sosial kultural 20 soal, dan wawancara 10 soal. Berikut adalah jadwal lengkap alur seleksi PPPK tahun 2023:</span></p><h3><span style="background-color: transparent; color: rgb(67, 67, 67);">Seleksi Administrasi</span></h3><ul><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengumuman seleksi: 16-30 September 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pendaftaran seleksi: 17 September – 6 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Seleksi administrasi: 17 September – 9 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengumuman hasil seleksi administrasi: 10-13 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Masa sanggah: 14-16 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Jawab sanggah: 14-18 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengumuman pascasanggah: 17-23 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Penarikan data final: 24-26 Oktober 2023</span></li></ul><h3><span style="background-color: transparent; color: rgb(67, 67, 67);">Seleksi Kompetensi</span></h3><ul><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Penjadwalan seleksi kompetensi: 27-30 Oktober 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengumuman daftar peserta, waktu, dan tempat seleksi kompetensi: 31 Oktober – 3 November 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pelaksanaan seleksi kompetensi: 5-29 November 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pelaksanaan seleksi kompetensi teknis tambahan: 10 November – 1 Desember 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengolahan nilai seleksi kompetensi: 25 November – 4 Desember 2023</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengumuman kelulusan: 1-10 Desember 2023</span></li></ul><h3><span style="background-color: transparent; color: rgb(67, 67, 67);">Penetapan DRH NI PPPK</span></h3><ul><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Pengisian DRH NI PPPK: 11 Desember 2023 – 9 Januari 2024</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Usul penetapan NI PPPK: 10 Januari – 8 Februari 2024</span></li></ul><h2><span style="background-color: transparent; color: rgb(0, 0, 0);">Formasi PPPK 2023</span></h2><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Pemerintah memberikan lebih banyak formasi bagi PPPK daripada PNS dalam pendaftaran seleksi PPPK tahun ini. Formasi CASN pemerintah pusat berjumlah 28.903 untuk CPNS dan 49.959 untuk PPPK. Di pemerintah daerah, tersedia formasi sebanyak 296.084 untuk PPPK guru, 154.724 untuk PPPK tenaga kesehatan, dan 42.826 untuk PPPK teknis. Kementerian dan pemerintah daerah telah mengumumkan formasi CPNS dan PPPK masing-masing, termasuk Kementerian Hukum dan HAM yang menyediakan 1.015 formasi CPNS dan 15.630 formasi PPPK, serta Kejaksaan Agung RI yang membuka 7.846 formasi untuk CPNS dan 249 formasi untuk PPPK. Pemkab Batanghari juga membuka 1.099 formasi PPPK, sedangkan Pemkab Bogor membuka 4.327 formasi PPPK, termasuk tenaga guru, tenaga kesehatan, dan tenaga teknis.</span></p><h2><span style="background-color: transparent; color: rgb(0, 0, 0);">Cara Melihat Formasi PPPK 2023</span></h2><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Untuk melihat informasi terbaru tentang formasi yang dibuka, kamu dapat menggunakan beberapa cara. Pertama, kamu bisa mencari berita lokal di daerahmu. Kamu juga bisa mengikuti akun media sosial resmi kementerian yang kamu minati untuk mendapatkan informasi terbaru. Selain itu, kamu dapat memantau formasi PPPK di semua instansi melalui laman SSCASN dengan langkah-langkah sebagai berikut:</span></p><ol><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Buka laman [https://data-sscasn.bkn.go.id/spf](https://data-sscasn.bkn.go.id/spf).</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Isi kolom kualifikasi yang sesuai dengan formasi yang kamu cari.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Isi semua kolom yang disediakan, mulai dari jenis pengadaan, instansi, dan tingkat pendidikan.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Klik "Cari."</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Sistem akan menampilkan formasi yang sesuai dengan kualifikasi yang kamu isi.</span></li></ol><h2><span style="background-color: transparent; color: rgb(0, 0, 0);">Persyaratan Pendaftaran PPPK 2023</span></h2><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Persyaratan pendaftaran PPPK 2023 dapat berbeda untuk setiap formasi atau instansi, terutama yang berkaitan dengan kompetensi atau pengalaman kerja. Namun, berikut adalah beberapa persyaratan umum yang perlu kamu siapkan:</span></p><h3><span style="background-color: transparent; color: rgb(67, 67, 67);">Syarat Pendaftaran PPPK Nonguru</span></h3><ul><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Tidak pernah dipidana dengan pidana penjara 2 tahun atau lebih.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Tidak pernah diberhentikan dengan hormat tidak atas permintaan sendiri atau dengan hormat sebagai PNS/Prajurit TNI/Kepolisian Negara RI.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Tidak pernah diberhentikan tidak dengan hormat sebagai pegawai swasta.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Tidak berkedudukan sebagai CPNS, PNS, prajurit TNI, atau anggota Kepolisian Negara RI.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Tidak menjadi anggota/pengurus partai politik (parpol) atau terlibat politik praktis.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Memiliki kualifikasi pendidikan sesuai dengan persyaratan jabatan.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Sehat jasmani dan rohani sesuai dengan persyaratan jabatan yang dilamar.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Bersedia ditempatkan di seluruh wilayah NKRI atau negara lain yang ditentukan oleh instansi pemerintah.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Batas usia pelamar PPPK non guru minimal adalah 20 tahun. Batas usia maksimal seleksi ini adalah 1 tahun sebelum batas usia tertentu pada jabatan yang dilamar sesuai dengan ketentuan peraturan perundang-undangan.</span></li></ul><h2><span style="background-color: transparent; color: rgb(0, 0, 0);">Syarat Pendaftaran PPPK Guru</span></h2><ul><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Honorer THK-2 sesuai database THK-2 di BKN.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Guru Honorer yang masih aktif mengajar di sekolah negeri di bawah kewenangan Pemerintah Daerah dan terdaftar sebagai guru di Dapodik Kemendikbud.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Guru yang masih aktif mengajar di sekolah swasta dan terdaftar sebagai guru di Dapodik Kemendikbud.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Lulusan Pendidikan Profesi Guru (PPG) yang belum menjadi guru dan terdaftar di Database Lulusan Pendidikan Profesi Guru Kemendikbud.</span></li><li><span style="background-color: transparent; color: rgb(0, 0, 0);">Batas usia pelamar seleksi PPPK guru paling rendah adalah 20 tahun dan paling tinggi adalah 59 tahun saat mendaftar.</span></li></ul><p><span style="background-color: transparent; color: rgb(0, 0, 0);">Selain persyaratan di atas, pastikan untuk membuat akun di [https://daftar-sscasn.bkn.go.id/login](https://daftar-sscasn.bkn.go.id/login) terlebih dahulu, karena semua tahapan seleksi akan dilakukan melalui laman tersebut. Ingatlah untuk selalu merujuk pada laman resmi pemerintah saat mencari informasi terkait seleksi calon ASN 2023.</span></p><p>Itulah ulasan tentang pendaftaran PPPK, jadwal, formasi dan persyaratannya. <span style="background-color: transparent; color: rgb(0, 0, 0);">Semoga informasi ini bermanfaat bagi kamu yang ingin mendaftar sebagai PPPK pada tahun 2023. Untuk informasi lebih lanjut, kamu bisa membaca artikel lainnya di QuBisa seperti artikel berjudul </span><a href="https://www.qubisa.com/article/jangan-keliru-ini-6-perbedaan-pppk-dan-pns"><span style="background-color: transparent; color: rgb(0, 0, 0);"><u>Jangan Keliru, Ini 6 Perbedaan PPPK dan PNS</u></span></a><span style="background-color: transparent; color: rgb(0, 0, 0);">.</span></p></article></div>```

**Comment by albirrkarim** [comment]
Thanks for the feedback. I have updated the package, please try again, paste your HTML string into [demo website](https://react-speech-highlight.vercel.app/)

**Comment by RubenManurung** [comment]
There are some issues in the package such as:
1.spoken word sometimes doesn't match the highlighted text.
example: string from prev issue.
2.abbreviations like SDM (read s underline dm)
example: ```<p><span style="background-color:transparent;color:#000000;">Kompetensi SDM mengacu pada kombinasi pengetahuan, keterampilan, sikap, dan perilaku yang diperlukan untuk mencapai kinerja yang unggul dalam pekerjaan. Ini melibatkan lebih dari sekadar kemampuan teknis, tetapi juga aspek-aspek seperti komunikasi efektif, kolaborasi, </span><a href="https://www.qubisa.com/article/gaya-kepemimpinan-dan-jenis-gaya-kepemimpinan"><span style="background-color:transparent;color:#000000;">kepemimpinan</span></a><span style="background-color:transparent;color:#000000;">, dan adaptabilitas. Memiliki karyawan dengan kompetensi yang tepat dapat membantu perusahaan mencapai tujuan bisnisnya dengan lebih efektif.</span></p>```
3.text that has a style has a break (italic, a href)
example: ```<p><span style="background-color:transparent;color:#000000;">Memiliki karyawan yang handal adalah aset dan modal dasar perusahaan untuk bisa berkembang lebih cepat. Untuk itu, perusahaan perlu berinvestasi menyelenggarakan training karyawan. Supaya proses pelatihan dan pengembangan karyawan ini berjalan lancar serta bisa mencapai hasil sesuai harapan, maka perlu memilih dan menerapkan </span><a href="https://www.qubisa.com/article/metode-pembelajaran-untuk-training-karyawan"><span style="background-color:transparent;color:#1155cc;"><u>metode pembelajaran untuk training karyawan</u></span></a><span style="background-color:transparent;color:#000000;"> yang efektif. Apa saja? Simak, yuk.</span></p>```
4.no Indonesian language available device samsung A53, OS android 13
5.on mobile android doesn't read the number 
for example the year 2023 is pronounced (year), September 7 is pronounced (September).
example: string from prev issue.

**Comment by albirrkarim** [comment]
1. Try again

2. Fixed

3.  The architecture is not support for that.

4.  see the FAQ [Why there's no voices available on the device?](https://github.com/albirrkarim/react-speech-highlight-demo#h-faq)

5.  see the FAQ [Why there's no voices available on the device?](https://github.com/albirrkarim/react-speech-highlight-demo#h-faq)

**Comment by albirrkarim** [comment]
now we support TTS using audio file, you can get the audio file from other provider like eleven labs, etc.  so the audio quality is human like voice.  

See the introduction section

https://github.com/albirrkarim/react-speech-highlight-demo?tab=readme-ov-file#a-introduction
