### ISSUE TITLE
Add support for autoscroll on a page

### ISSUE THREAD

**Issue by wassim** [albirrkarim/react-speech-highlight-demo#5]
Is there a chance that you add autoscroll support for React? Maybe by using SpeechSynthesisUtterance?

**Comment by albirrkarim** [comment]
<img width="1424" alt="Screenshot 2024-08-23 at 17 50 38" src="https://github.com/user-attachments/assets/582296b7-5458-4387-bf01-bead78e60bc3">

![feature overview](https://raw.githubusercontent.com/albirrkarim/react-speech-highlight-demo/main/img/features.png)

**Comment by albirrkarim** [comment]
it has auto scroll
